#!/bin/bash
echo "🔍 Verificando estado REAL de Firestore..."
echo ""
echo "1️⃣  Verificando si Firestore está habilitado en el proyecto..."
echo "   URL: https://console.firebase.google.com/project/sntss-e2117/firestore"
echo ""
echo "2️⃣  Si ves datos en la consola pero la API dice que no existe,"
echo "    puede ser que Firestore esté en modo 'Native' pero no completamente inicializado."
echo ""
echo "3️⃣  SOLUCIÓN: Ve a Firebase Console y:"
echo "    a) Ve a Firestore → Data"
echo "    b) Si NO ves ninguna colección, crea una colección de prueba llamada 'test'"
echo "    c) Crea un documento con ID 'test1' y campo 'value: 1'"
echo "    d) Esto fuerza la inicialización completa de Firestore"
echo ""
echo "4️⃣  Luego vuelve a probar el login"
